In [4]:
import numpy as np

In [8]:
myList = [[1,2,3], [4,5,6], [7,8,9]]

In [21]:
np.arange(2, 20, 3)

array([ 2,  5,  8, 11, 14, 17])

In [22]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
np.linspace(1,15,6)

array([ 1. ,  3.8,  6.6,  9.4, 12.2, 15. ])

In [29]:
myArray = np.arange(12)
myArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [41]:
my2DArray = myArray.reshape(4, 3)
my2DArray

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [42]:
myArray[0:7]

array([0, 1, 2, 3, 4, 5, 6])

In [43]:
my2DArray[2][2]

8

In [45]:
my2DArray[1:3,1:3]

array([[4, 5],
       [7, 8]])

In [47]:
rollNumbers = [2,3,21,7,6,5,9]
np.array(rollNumbers)

array([ 2,  3, 21,  7,  6,  5,  9])

In [50]:
subArray = rollNumbers[0:3]
subArray

[2, 3, 21]

In [54]:
subArray = [7, 7, 7]
subArray

[7, 7, 7]

In [55]:
rollNumbers

[2, 3, 21, 7, 6, 5, 9]

In [63]:
newArray = np.arange(3,10)
copyArray = newArray.copy()
copyArray

array([3, 4, 5, 6, 7, 8, 9])

In [64]:
slicedArray = newArray[0:4]
slicedArray

array([3, 4, 5, 6])

In [65]:
slicedArray[:] = 777

In [66]:
slicedArray

array([777, 777, 777, 777])

In [67]:
newArray

array([777, 777, 777, 777,   7,   8,   9])

In [68]:
copyArray

array([3, 4, 5, 6, 7, 8, 9])

In [69]:
copyArray[copyArray > 7]

array([8, 9])

In [70]:
copyArray * 2

array([ 6,  8, 10, 12, 14, 16, 18])

In [71]:
copyArray + 10

array([13, 14, 15, 16, 17, 18, 19])

In [72]:
np.sqrt(copyArray)

array([1.73205081, 2.        , 2.23606798, 2.44948974, 2.64575131,
       2.82842712, 3.        ])

In [73]:
a = [1, 2, 3]
b = [4, 5, 6]

np.cross(a, b)

array([-3,  6, -3])

In [76]:
np.dot(a, b)

32

In [77]:
matrix = [[0,1],[2,3]]
np.transpose(matrix)

array([[0, 2],
       [1, 3]])

In [78]:
np.mean(matrix)

1.5

In [79]:
np.std(matrix)

1.118033988749895

In [80]:
np.cov(matrix)

array([[0.5, 0.5],
       [0.5, 0.5]])